import os
from dotenv import load_dotenv

load_dotenv()

AZURE_STORAGE_CONNECTION_STRING = os.getenv('AZURE_STORAGE_CONNECTION_STRING')
AZURE_CONTAINER_NAME = os.getenv('AZURE_CONTAINER_NAME')
CONFLUENCE_TOKEN = os.getenv('CONFLUENCE_API_TOKEN')
CONFLUENCE_USER = os.getenv('CONFLUENCE_USER')
PARENT_PAGE_ID = os.getenv('PARENT_PAGE_ID')
CONFLUENCE_BASE_URL = os.getenv('CONFLUENCE_BASE_URL')
